name: Telegram Smoke
on: { workflow_dispatch: {} }
jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Send telegram (notify.py)
        run: |
          python scripts/notify.py "🔔 Telegram smoke from GitHub Actions"

